?rnorm()
rnorm(n=5, sd=8, mean=3)
?c()
?seq()
seq(from=10, to=33, length.out = 100)

x <- c("a", "b", "c")
A <- seq(from=10, to=20, along.with = x)
sqrt(A)
?rep()
?print()
?is.numeric()
?is.integer()
?is.double()
?is.character()
?typeof()
?sqrt()
?paste()